### ISSUE TITLE
Komentarze nie działają proszę naprawcie asap (Kamil mi kazał nie bijcie)

### ISSUE THREAD

**Issue by f10k1** [skni-kod/SKNIKodBackEndServer#27]
Dodatkowo:
W projektach ma nie być komentarzy
Brak opcji dodania komentarza do komentarza (jeden poziom zagnieżdżenia)
Komentarze pasowało by paginować

**Comment by SzateX** [comment]
@Str34kk W ramach tego Issue zajmij się tym co się tam dzieje + zrób zagnieżdzenia komentarzy (1 poziom).

Deadline: 11.03.2021
