### ISSUE TITLE
Endpoint /api/project/{id}/ - poprawki

### ISSUE THREAD

**Issue by km2442** [skni-kod/SKNIKodBackEndServer#4]
"repository_link" - endpoint przyjmuje pojedynczy link jako string - należy zamienić to tak, aby przyjmowało wiele linków, wraz z typem linku (enum jako string)
"authors" - przyjmuje tablice stringów - nie wiem jak to działa - powinno przyjmować tablicę z user_id autorów projektu

**Comment by SzateX** [comment]
Przetestuj, tylko zrób migracje

**Comment by km2442** [comment]
Po migracji docsy nie działają
