### ISSUE TITLE
Refactor widoku grup

### ISSUE THREAD

**Issue by SzateX** [skni-kod/SKNIKodBackEndServer#5]
Deadline: 29.12.2020

**Comment by Kazan1520** [comment]
Utworzono 2 nowe klasy do widoku grup - dla listy oraz dla pojedynczego. Pojedynczy - metody: GET, PUT, DELETE, PATCH. Lista - metody: GET, POST.

**Comment by SzateX** [comment]
Przepnij widoki pod poprawne urle

**Comment by Kazan1520** [comment]
Zrobione
