### ISSUE TITLE
Zapamiętywanie przez artykuł zdjęć jakie zostały w nim dodane

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIKodBackEndServer#50]
Należy dodać możliwość zapamiętania w bazie powiązania jeden do wielu: <artykuł>-<obrazek w treści artykułu>. Front end potrzebuje możliwości wyświetlania podczas edycji artykułu jakie obrazki był w nim dodane oraz wyświetlania obrazków z treści w galerii.

Powiązane ze zgłoszeniami z front-endu i potrzebne do ich wykonania:
https://github.com/skni-kod/SKNIFrontEnd/issues/23
https://github.com/skni-kod/SKNIFrontEnd/issues/24

**Comment by SzateX** [comment]
Porównaj z #52
