### ISSUE TITLE
Niemożliwość dodania linków do projektu

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIKodBackEndServer#51]
Aktualnie nie można dodać linku do GitHub'a i innych stron do projektu. Dodanie powoduje, że link się nie pojawia.
Wygląda to tak jakby baza danych nie posiadała odpowiedniego pola do ich przechowywania.

**Comment by AzuxDario** [comment]
Wymagane przez: https://github.com/skni-kod/SKNIFrontEnd/issues/32

**Comment by SzateX** [comment]
Mam pytanko @AzuxDario 
Też po kliknięciu przycisku dodaj link nie wyświetla się nic tylko dostajesz błąd w konsoli?

![obraz](https://user-images.githubusercontent.com/10698770/143315530-691ae462-eb24-43ee-93cd-ce033127fbe1.png)

**Comment by AzuxDario** [comment]
Sprawdziłem, jak dodaję nowy projekt jest tak jak masz ale gdy edytuje obecny, mogę dodać link tym przyciskiem ale i tak się nie zapisuje.

**Comment by SzateX** [comment]
Dobra, zamykam ze względu na to, że obsługa po stronie frontendu jest niepoprawna:

Należy skorzystać z przy dodawaniu/edytowaniu z api zgodnie z REST:
api/generic_links/ (POST/PATCH/DELETE)

Podając następujące dane:
link - url,
link_type - dostępne: GITHUB, GITLAB, BITBUCKET, BLOG, PORTFOLIO, OTHER
linked_object - id utworzonego obiektu
content_type - dostępne: project, article, profile

Po takim zabiegu wraz z danymi projektu (niezgodne z REST), otrzymujemy 
![obraz](https://user-images.githubusercontent.com/10698770/143321202-6a23f602-e82f-482c-932b-a7f7848874ff.png)
