### ISSUE TITLE
Dodawanie obrazków z treści do galerii

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIKodBackEndServer#52]
Po wykonaniu issue https://github.com/skni-kod/SKNIKodBackEndServer/issues/50 należy dodać w bazie informację czy dany obrazek z treści ma się wyświetlać w galerii.

Wymagane przez  issue z front endu:
https://github.com/skni-kod/SKNIFrontEnd/issues/24

**Comment by SzateX** [comment]
Zalecane rozwiązanie:

Dodanie kolejnej encji, która przechowywać będzie dla każdego wpisu z Gallery informację o trybach wyświetlania:
- tekst (bool)
- galeria (bool)
- miniaturka (bool)

Dodatkowo jeżeli chodzi o #50 to takie powiązanie jest już zrobione przez Encję Gallery oraz klucz obcy w artykule.
