### ISSUE TITLE
Dodatkowy enum do artykułów

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIKodBackEndServer#58]
Należy dodać do artykułów enum opisujący do jakiej grupy artykuł należy. Obecnie potrzebne są dwie wartości: News, Article.
Dodatkowo potrzebny jest endpoint do zwrócenia możliwych typów artykułu, aby na froncie dało się wybrać typ przy tworzeniu artykułu.

**Comment by Kazan1520** [comment]
Done
