### ISSUE TITLE
Refactor widoku użytkowników

### ISSUE THREAD

**Issue by SzateX** [skni-kod/SKNIKodBackEndServer#6]
Deadline: 4.01.2021r.

**Comment by Str34kk** [comment]
Utworzyłem pull request. Nie byłem w stanie przetestować metod POST z listy oraz PUT DELETE PATCH z detailsów więc nie mam pewności czy wszystko działa poprawnie. metody GET działają tak jak powinny

**Comment by SzateX** [comment]
Dlaczego nie byłeś w stanie przetestować? Jakiś błąd wyskoczył?
